# 1. Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smartedms
spring.datasource.username=postgres
spring.datasource.password=smartedms123
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình JPA / Hibernate (Tự động tạo bảng từ code Java)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Cấu hình Server Port
server.port=8080

















# --- Cấu hình JWT ---
# Thời gian hết hạn (86400000 ms = 24 giờ)
jwt.expiration=86400000

# Secret Key (Đây là giá trị mặc định cho môi trường DEV)
# Lưu ý: Key phải đủ dài (ít nhất 32 ký tự) để thuật toán HS256 không báo lỗi
jwt.secret=DayLaMotDoanMaBiMatRatDaiDeDamBaoBaoMatChoDuAnSmartEDMS123
